# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/Demo_HW/Demo_HW.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW || ORIG_REF_NAME==Demo_HW} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_microblaze_0_0/Demo_HW_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_microblaze_0_0 || ORIG_REF_NAME==Demo_HW_microblaze_0_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_dlmb_v10_0/Demo_HW_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_dlmb_v10_0 || ORIG_REF_NAME==Demo_HW_dlmb_v10_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_ilmb_v10_0/Demo_HW_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_ilmb_v10_0 || ORIG_REF_NAME==Demo_HW_ilmb_v10_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_dlmb_bram_if_cntlr_0/Demo_HW_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Demo_HW_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_ilmb_bram_if_cntlr_0/Demo_HW_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Demo_HW_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_lmb_bram_0/Demo_HW_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_lmb_bram_0 || ORIG_REF_NAME==Demo_HW_lmb_bram_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_xbar_0/Demo_HW_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_xbar_0 || ORIG_REF_NAME==Demo_HW_xbar_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_microblaze_0_axi_periph_0/Demo_HW_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Demo_HW_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_microblaze_0_axi_intc_0/Demo_HW_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Demo_HW_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_microblaze_0_xlconcat_0/Demo_HW_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Demo_HW_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_mdm_1_0/Demo_HW_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_mdm_1_0 || ORIG_REF_NAME==Demo_HW_mdm_1_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_clk_wiz_1_0/Demo_HW_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_clk_wiz_1_0 || ORIG_REF_NAME==Demo_HW_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_rst_clk_wiz_1_100M_0/Demo_HW_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Demo_HW_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_mig_7series_0_0/Demo_HW_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_mig_7series_0_0 || ORIG_REF_NAME==Demo_HW_mig_7series_0_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_mii_to_rmii_0_0/Demo_HW_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_mii_to_rmii_0_0 || ORIG_REF_NAME==Demo_HW_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_axi_uartlite_0_0/Demo_HW_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_axi_uartlite_0_0 || ORIG_REF_NAME==Demo_HW_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_axi_ethernetlite_0_0/Demo_HW_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_axi_ethernetlite_0_0 || ORIG_REF_NAME==Demo_HW_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_axi_timer_0_0/Demo_HW_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_axi_timer_0_0 || ORIG_REF_NAME==Demo_HW_axi_timer_0_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_axi_smc_0/Demo_HW_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_axi_smc_0 || ORIG_REF_NAME==Demo_HW_axi_smc_0} -quiet] -quiet

# IP: bd/Demo_HW/ip/Demo_HW_rst_mig_7series_0_81M_0/Demo_HW_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_HW_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==Demo_HW_rst_mig_7series_0_81M_0} -quiet] -quiet

# XDC: bd/Demo_HW/Demo_HW_ooc.xdc
