# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Callum/Repository_Code/ECE532/Warmup_Demo_Group_Task/Warmup_Demo_Hardware/HW/HW.srcs/sources_1/bd/Demo_HW/ip/Demo_HW_microblaze_0_0/Demo_HW_microblaze_0_0.xci
# IP: The module: 'Demo_HW_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Callum/Repository_Code/ECE532/Warmup_Demo_Group_Task/Warmup_Demo_Hardware/HW/HW.srcs/sources_1/bd/Demo_HW/ip/Demo_HW_microblaze_0_0/Demo_HW_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_HW_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Callum/Repository_Code/ECE532/Warmup_Demo_Group_Task/Warmup_Demo_Hardware/HW/HW.srcs/sources_1/bd/Demo_HW/ip/Demo_HW_microblaze_0_0/Demo_HW_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_HW_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Callum/Repository_Code/ECE532/Warmup_Demo_Group_Task/Warmup_Demo_Hardware/HW/HW.srcs/sources_1/bd/Demo_HW/ip/Demo_HW_microblaze_0_0/Demo_HW_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_HW_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Callum/Repository_Code/ECE532/Warmup_Demo_Group_Task/Warmup_Demo_Hardware/HW/HW.srcs/sources_1/bd/Demo_HW/ip/Demo_HW_microblaze_0_0/Demo_HW_microblaze_0_0.xci
# IP: The module: 'Demo_HW_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Callum/Repository_Code/ECE532/Warmup_Demo_Group_Task/Warmup_Demo_Hardware/HW/HW.srcs/sources_1/bd/Demo_HW/ip/Demo_HW_microblaze_0_0/Demo_HW_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_HW_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Callum/Repository_Code/ECE532/Warmup_Demo_Group_Task/Warmup_Demo_Hardware/HW/HW.srcs/sources_1/bd/Demo_HW/ip/Demo_HW_microblaze_0_0/Demo_HW_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_HW_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Callum/Repository_Code/ECE532/Warmup_Demo_Group_Task/Warmup_Demo_Hardware/HW/HW.srcs/sources_1/bd/Demo_HW/ip/Demo_HW_microblaze_0_0/Demo_HW_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_HW_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
